package com.lvy.appexec.drools;

//import com.lvy.appexec.drools.Clock;

rule "run"
   salience 1
   when
      c: Clock(!(hour == 1 && second == 1))
   then
      System.out.println(c);
      try {
        Thread.sleep(1000);
      } catch (InterruptedException e) {
         e.printStackTrace();
      }
      c.setSecond(c.getSecond() + 1);
      update(c);
end

rule "second"
   salience 2
   when
      c: Clock(second == 60);
   then
      c.setMinute(c.getMinute() + 1);
      c.setSecond(0);
      update(c);
end

rule "minute"
   salience 3
   when
       c:Clock(minute == 60)
   then
       c.setHour(c.getHour() + 1);
       c.setMinute(0);
       update(c);
end
